version: "3"
services:
  web-app:
    build: .
    container_name: 'tp3_api'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - /home/hernan/bdnsql/tp3/api:/api
    depends_on:
      - "db-redis"

  db-redis:
    container_name: 'db_tp3_api'
    image: redis
    ports:
      - "6379:6379"